import numpy as np
import pandas as pd
import joblib
import requests
import json
from flask import  Flask, request,jsonify,render_template
from flask_cors import CORS,cross_origin
import pandas as pd
from statistics import mean
import pickle

dataset_symptoms = [
  "Abdomen acute",
  "Abdominal bloating",
  "Abdominal tenderness",
  "Abnormal sensation",
  "Abnormally hard consistency",
  "Abscess bacterial",
  "Absences finding",
  "Achalasia",
  "Ache",
  "Adverse effect",
  "Adverse reaction",
  "Agitation",
  "Air fluid level",
  "Alcohol binge episode",
  "Alcoholic withdrawal symptoms",
  "Ambidexterity",
  "Angina pectoris",
  "Anorexia",
  "Anosmia",
  "Aphagia",
  "Apyrexial",
  "Arthralgia",
  "Ascites",
  "Asterixis",
  "Asthenia",
  "Asymptomatic",
  "Ataxia",
  "Atypia",
  "Aura",
  "Awakening early",
  "Barking cough",
  "Bedridden",
  "Behavior hyperactive",
  "Behavior showing increased motor activity",
  "Blackout",
  "Blanch",
  "Bleeding of vagina",
  "Bowel sounds decreased",
  "Bradycardia",
  "Bradykinesia",
  "Breakthrough pain",
  "Breath sounds decreased",
  "Breath-holding spell",
  "Breech presentation",
  "Bruit",
  "Burning sensation",
  "Cachexia",
  "Cardiomegaly",
  "Cardiovascular event",
  "Cardiovascular finding",
  "Catatonia",
  "Catching breath",
  "Charleyhorse",
  "Chest discomfort",
  "Chest tightness",
  "Chill",
  "Choke",
  "Cicatrisation",
  "Clammy skin",
  "Claudication",
  "Clonus",
  "Clumsiness",
  "Colic abdominal",
  "Consciousness clear",
  "Constipation",
  "Coordination abnormal",
  "Cough",
  "Cushingoid facies",
  "Cushingoidhabitus",
  "Cyanosis",
  "Adverse reaction",
  "Agitation",
  "Air fluid level",
  "Alcohol binge episode",
  "Alcoholic withdrawal symptoms",
  "Ambidexterity",
  "Angina pectoris",
  "Anorexia",
  "Anosmia",
  "Aphagia",
  "Cystic lesion",
  "Debilitation",
  "Abdomen acute",
  "Abdominal bloating",
  "Abdominal tenderness",
  "Abnormal sensation",
  "Abnormally hard consistency",
  "Abscess bacterial",
  "Absences finding",
  "Decompensation",
  "Decreased body weight",
  "Decreased stool caliber",
  "Decreased translucency",
  "Diarrhea",
  "Difficulty",
  "Difficulty passing urine",
  "Disequilibrium",
  "Distended abdomen",
  "Distress respiratory",
  "Disturbed family",
  "Dizziness",
  "Dizzy spells",
  "Drool",
  "Drowsiness",
  "Dry cough",
  "Dullness",
  "Decompensation",
  "Decreased body weight",
  "Decreased stool caliber",
  "Decreased translucency",
  "Diarrhea",
  "Difficulty",
  "Difficulty passing urine",
  "Disequilibrium",
  "Distended abdomen",
  "Distress respiratory",
  "Dysarthria",
  "Dysdiadochokinesia",
  "Dysesthesia",
  "Dyspareunia",
  "Dyspnea",
  "Dyspnea on exertion",
  "Dysuria",
  "Ecchymosis",
  "Egophony",
  "Elation",
  "Emphysematous change",
  "Energy increased",
  "Enuresis",
  "Erythema",
  "Estrogen use",
  "Excruciating pain",
  "Exhaustion",
  "Extrapyramidal sign",
  "Extreme exhaustion",
  "Facial paresis",
  "Fall",
  "Fatigability",
  "Dyspnea on exertion",
  "Dysuria",
  "Ecchymosis",
  "Egophony",
  "Elation",
  "Emphysematous change",
  "Energy increased",
  "Enuresis",
  "Erythema",
  "Estrogen use",
  "Excruciating pain",
  "Exhaustion",
  "Extrapyramidal sign",
  "Extreme exhaustion",
  "Facial paresis",
  "Fall",
  "Fatigability",
  "Fatigue",
  "Fear of falling",
  "Fecaluria",
  "Feces in rectum",
  "Feeling hopeless",
  "Feeling strange",
  "Feeling suicidal",
  "Feels hot/feverish",
  "Fever",
  "Flare",
  "Flatulence",
  "Floppy",
  "Flushing",
  "Focal seizures",
  "Food intolerance",
  "Formication",
  "Frail",
  "Fremitus",
  "Frothy sputum",
  "Feeling hopeless",
  "Feeling strange",
  "Feeling suicidal",
  "Feels hot/feverish",
  "Fever",
  "Flare",
  "Flatulence",
  "Floppy",
  "Flushing",
  "Focal seizures",
  "Food intolerance",
  "Formication",
  "Frail",
  "Fremitus",
  "Frothy sputum",
  "Gag",
  "Gasping for breath",
  "General discomfort",
  "General unsteadiness",
  "Giddy mood",
  "Gravida 0",
  "Gravida 10",
  "Green sputum",
  "Groggy",
  "Guaiac positive",
  "Gurgle",
  "Hacking cough",
  "Haemoptysis",
  "Haemorrhage",
  "Hallucinations auditory",
  "Hallucinations visual",
  "Has religious belief",
  "Headache",
  "Heartburn",
  "Heavy feeling",
  "Heavy legs",
  "Heberden's node",
  "Hematochezia",
  "Hematocrit decreased",
  "Hematuria",
  "Heme positive",
  "Hemianopsia homonymous",
  "Hemiplegia",
  "Hemodynamically stable",
  "Hepatomegaly",
  "Hepatosplenomegaly",
  "Hirsutism",
  "History of - blackout",
  "Hoard",
  "Hoarseness",
  "Homelessness",
  "Homicidal thoughts",
  "Hot flush",
  "Hunger",
  "Hydropneumothorax",
  "Hyperacusis",
  "Hypercapnia",
  "Hyperemesis",
  "Hyperhidrosis disorder",
  "Hyperkalemia",
  "Hypersomnia",
  "Hypersomnolence",
  "Hypertonicity",
  "Hyperventilation",
  "Hypesthesia",
  "Hypoalbuminemia",
  "Hypocalcemia result",
  "Hypokalemia",
  "Hypokinesia",
  "Gurgle",
  "Hacking cough",
  "Haemoptysis",
  "Haemorrhage",
  "Hallucinations auditory",
  "Hallucinations visual",
  "Has religious belief",
  "Headache",
  "Heartburn",
  "Heavy feeling",
  "Heavy legs",
  "Heberden's node",
  "Hypometabolism",
  "Hyponatremia",
  "Hypoproteinemia",
  "Hypotension",
  "Hypothermia, natural",
  "Hypotonic",
  "Hypoxemia",
  "Immobile",
  "Impaired cognition",
  "Inappropriate affect",
  "Incoherent",
  "Indifferent mood",
  "Intermenstrual heavy bleeding",
  "Intoxication",
  "Irritable mood",
  "Jugular venous distention",
  "Labored breathing",
  "Lameness",
  "Large-for-dates fetus",
  "Leftatrialhypertrophy",
  "Lesion",
  "Lethargy",
  "Lightheadedness",
  "Lip smacking",
  "Loose associations",
  "Loss of taste or smell",
  "Low back pain",
  "Lung nodule",
  "Macerated skin",
  "Macule",
  "Malaise",
   "Impaired cognition",
  "Inappropriate affect",
  "Incoherent",
  "Indifferent mood",
  "Intermenstrual heavy bleeding",
  "Intoxication",
  "Irritable mood",
  "Jugular venous distention",
  "Labored breathing",
  "Lameness",
  "Mass in breast",
  "Mass of body structure",
  "Mediastinal shift",
  "Mental status changes",
  "Metastatic lesion",
  "Milky",
  "Moan",
  "Monoclonal",
  "Monocytosis",
  "Mood depressed",
  "Moody",
  "Motor retardation",
  "Murphy's sign",
  "Muscle hypotonia",
  "Muscle twitch",
  "Myalgia",
  "Mydriasis",
  "Myoclonus",
  "Nasal discharge present",
  "Nasal flaring",
  "Nausea",
  "Nausea and vomiting",
  "Neck stiffness",
  "Neologism",
  "Nervousness",
  "Night sweat",
  "Nightmare",
  "No known drug allergies",
  "No status change",
  "Noisy respiration",
  "Non-productive cough",
  "Nonsmoker",
  "Numbness",
  "Numbness of hand",
  "Oliguria",
  "Orthopnea",
  "Orthostasis",
  "Out of breath",
  "Overweight",
  "Pain",
   "Moody",
  "Motor retardation",
  "Murphy's sign",
  "Muscle hypotonia",
  "Muscle twitch",
  "Myalgia",
  "Mydriasis",
  "Myoclonus",
  "Nasal discharge present",
  "Nasal flaring",
  "Nausea",
  "Nausea and vomiting",
  "Neck stiffness",
  "Neologism",
  "Nervousness",
  "Pain abdominal",
  "Pain back",
  "Pain chest",
  "Pain foot",
  "Pain in lower limb",
  "Pain neck",
  "Painful swallowing",
  "Pallor",
  "Palpitation",
  "Panic",
  "Paresis",
  "Paresthesia",
  "Passed stones",
  "Patient non compliance",
  
  "Pneumatouria",
  "Polydypsia",
  "Polymyalgia",
  "Polyuria",
  "Poor dentition",
  "Poor feeding",
  "Posteriorrhinorrhea",
  "Posturing",
  "Presence of q wave",
  "Pressure chest",
  "Previous pregnancies 2",
  "Primigravida",
  "Prodrome",
  "Productive cough",
  "Projectile vomiting",
  "Prostate tender",
  "Prostatism",
  "Proteinemia",
  "Pruritus",
  "Pulse absent",
  "Pulsusparadoxus",
  "Pustule",
  "Qt interval prolonged",
  "R wave feature",
  "Rale",
  "Rambling speech",
  "Rapid shallow breathing",
  "Red blotches",
  "Redness",
  "Regurgitates after swallowing",
  "Renal angle tenderness",
  "Rest pain",
  "Retch",
  "Retropulsion",
  "Rhd positive",
  "Rhonchus",
  "Rigor - temperature-associated observation",
  "Rolling of eyes",
  "Room spinning",
  "Satiety early",
  "Scar tissue",
  "Sciatica",
  "Scleralicterus",
  "Scratch marks",
  "Sedentary",
  "Seizure",
  "Sensory discomfort",
  "Shooting pain",
  "Shortness of breath",
  "Side pain",
  "Sinus rhythm",
  "Sleeplessness",
  "Sleepy",
  "Slowing of urinary stream",
  "Sneeze",
  "Sniffle",
  "Snore",
  "Snuffle",
  "Soft tissue swelling",
  "Sore to touch",
  "Spasm",
  "Speech slurred",
  "Splenomegaly",
  "Spontaneous rupture of membranes",
  "Sputum purulent",
  "St segment depression",
  "St segment elevation",
  "Stahli's line",
  "Stiffness",
  "Stinging sensation",
  "Stool color yellow",
  "Stridor",
  "Stuffy nose",
  "Stupor",
  "Suicidal",
  "Superimposition",
  "Sweat",
  "Sweating increased",
  "Swelling",
  "Symptom aggravating factors",
  "Syncope",
  "Systolic ejection murmur",
  "Systolic murmur",
  "T wave inverted",
  "Tachypnea",
  "Tenesmus",
  "Terrify",
  "Thicken",
  "Throat sore",
  "Throbbing sensation quality",
  "Tinnitus",
  "Titubation",
  "Todd paralysis",
  "Tonic seizures",
  "Transaminitis",
  "Transsexual",
  "Tremor",
  "Tremor resting",
  "Tumor cell invasion",
  "Unable to concentrate",
  "Unconscious state",
  "Uncoordination",
  "Underweight",
  "Unhappy",
  "Unresponsiveness",
  "Unsteady gait",
  "Unwell",
  "Urge incontinence",
  "Urgency of micturition",
  "Urinary hesitation",
  "Urinoma",
  "Verbal auditory hallucinations",
  "Verbally abusive behavior",
  "Vertigo",
  "Vision blurred",
  "Vomiting",
  "Weepiness",
  "Weight gain",
  "Welt",
  "Wheelchair bound",
  "Wheezing",
  "Withdraw",
  "Worry",
  "Yellow sputum",
]
app = Flask(__name__)
# rf_model = joblib.load('Rf_Disease.joblib')
# load_model = pickle.load(open('Rf_Disease.joblib', 'rb'))

with open('Rf_Disease.sav', 'rb') as file:
    rf_model = pickle.load(file)

df_norm = pd.read_csv("dis_sym_dataset_norm.csv") # Individual Disease

Y = df_norm.iloc[:, 0:1]

cors = CORS(app)
app.config['CORS_HEADERS'] = 'Content-Type'


@cross_origin() 
@app.route('/api',methods=['POST'])
def predict_disease():
     if request.method == 'POST':
        
        data_array = request.json['symptoms']
        sample_x = [0 for x in range(0,len(dataset_symptoms))]
        for val in data_array:
            sample_x[dataset_symptoms.index(val)]=1
        # print(data_array)
        # data = request.get_json(force=True)
        prediction = rf_model.predict_proba([sample_x])
        # print(prediction)
        diseases = list(set(Y['label_dis']))
        diseases.sort()
        k = 10
        topk = prediction[0].argsort()[-k:][::-1]
        # print(f"\nTop {k} diseases predicted based on symptoms")
        topk_dict = {}
        # Show top 10 highly probable disease to the user.
        for idx,t in  enumerate(topk):
            match_sym=set()
            row = df_norm.loc[df_norm['label_dis'] == diseases[t]].values.tolist()
            row[0].pop(0)

            for idx,val in enumerate(row[0]):
                if val!=0:
                    match_sym.add(dataset_symptoms[idx])
            prob = (len(match_sym.intersection(set(data_array)))+1)/(len(set(data_array))+1)
            # prob *= mean(scores)
            topk_dict[t] = prob
            j = 0
            topk_index_mapping = {}
            topk_sorted = dict(sorted(topk_dict.items(), key=lambda kv: kv[1], reverse=True))
            # for key in topk_sorted:
            #     prob = topk_sorted[key]*100
            #     topk_index_mapping[j] = key
            #     j += 1
            #     print(str(j) + " Disease name:",diseases[key], "\tProbability:",str(round(prob, 2))+"%")
        print(topk_dict)
        result = {}

        for key in topk_dict:
            result[dataset_symptoms[key]] = topk_dict[key]
        


        print(result)

        return result

if __name__ == '__main__':
    app.run(port=5000, debug=True)